### ISSUE TITLE
Installation fails for standalone usage

### ISSUE THREAD

**Issue by lauthiamkok** [zendframework/zend-expressive#183]
Following the guide here http://zend-expressive.readthedocs.org/en/stable/quick-start/. It fails to install with composer:

composer require zendframework/zend-expressive zendframework/zend-expressive-fastroute zendframework/zend-servicemanager

Error:

```
C:\...\test>composer require zendfra
mework/zend-expressive zendframework/zend-expressive-fastroute zendframework/zen
d-servicemanager
Using version ^0.5.3 for zendframework/zend-expressive
Using version ^0.2.0 for zendframework/zend-expressive-fastroute
Using version ^2.6 for zendframework/zend-servicemanager
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for zendframework/zend-expressive-fastroute ^0.2.0 ->
 satisfiable by zendframework/zend-expressive-fastroute[0.2.0].
    - zendframework/zend-expressive-fastroute 0.2.0 requires zendframework/zend-
expressive ^1.0@rc -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

Installation failed, deleting ./composer.json.
```

**Comment by moderndeveloperllc** [comment]
This has to do with composer setting `minimum-stability` to `stable` by default. 0.5.3 is the latest "stable" version, while zend-expressive-fastroute requires the newer `rc` version. I would strongly advise using the skeleton installer: https://github.com/zendframework/zend-expressive-skeleton that deals with this and more seamlesly.

If for some reason you don't want to to that, use:
```
composer require zendframework/zend-expressive-fastroute zendframework/zend-servicemanager`
```
The fastroute package has the correct dependency, and all will be installed properly.

**Comment by lauthiamkok** [comment]
why is it set to default. 0.5.3?  what is the latest of Expressive btw?

**Comment by moderndeveloperllc** [comment]
The latest tagged version is [1.0.0rc2](https://github.com/zendframework/zend-expressive/tree/1.0.0rc2). Since this is a [release candidate](https://en.wikipedia.org/wiki/Software_release_life_cycle#Release_candidate) version, composer does not, by default, pick that version when you do a simple `composer zendframework/zend-expressive`. To [specify a particular version](https://getcomposer.org/doc/03-cli.md#require), and not just the latest "stable" release, you can do something like `composer zendframework/zend-expressive:^1.0@rc` - which is what `zend-expressive-fastroute` uses in it's [composer.json](https://github.com/zendframework/zend-expressive-fastroute/blob/master/composer.json) file.

**Comment by weierophinney** [comment]
Unfortunately, we're in a crazy state right now, due to the release candidate. Composer only recently started defaulting to 0.x versions as latest stable when RCs appear (which is good; it's better than things completely blowing up when installing via the skeleton!), but it makes the standalone install quite difficult until we have stable 1.0 versions.

For now, you need to look at the various subcomponent changelogs to see what versions given tags are supporting, and install them individually, or ensure you provide the version strings. As examples:

```bash
# Install latest "stable" versions:
$ composer require "zendframework/zend-expressive:^0.5" "zendframework/zend-expressive-fastroute:^0.1.1"
```

Or:

```bash
# Install RC and compatible packages:
$ composer require "zendframework/zend-expressive:^1.0.0RC1" "zendframework/zend-expressive-fastroute:^0.2"
```

(I've tested each of these, and they work fine.)

This is not something we can actually "fix", but once the RC status is done, it won't be an issue. It doesn't make sense for us to update the install instructions, as it'll be too easy for those to go out of date.
