### ISSUE TITLE
Increase interoperability by using vendor/package config keys

### ISSUE THREAD

**Issue by sandrokeil** [zendframework/zend-expressive#188]
Some config keys have a vendor and/or package name like `whoops` or `zend-expressive` and some config keys have an independent name like `templates` or `routes`. There exists a discussion #155 about config structure, but it seems to be only a Cookbook. 

Is there a special reason why not every config key has a vendor/package name?

What is if we add module support like ZF2 has and each module can have it's own template renderer and it's own router or it's own DI container configuration? The `template` configuration for example, has for each template engine it's own option keys, but uses the same main config key name.

I think the following config structure makes more sense, because there is no way to support different libraries with one config structure. With this structure, it is also possible to switch between implementations by changing the factories or to use different renderer, DI or router in one application.

``` php
return [
    // vendor name
    'twig' => [
        // package name
        'view' => [ /* options */ ],
    ],
     // vendor name
    'zend' => [
        // package name
        'view' => [ /* options */ ],
        // package name
        'service-manager' => [ /* options */ ],
        // package name
        'expressive' => [ /* options */ ],
        ],
    ],
];
```

Maybe the complexity is higher, but it's better to understand for the user and it's more flexible. It exists a [PSR config proposal](https://github.com/php-fig/fig-standards/pull/620) which defines the config structure. The config structure is important.

**Comment by Maks3w** [comment]
1. Put limitations on config key names prevent drop in replacements by libraries which aim to fork/extend the original.
2. If you want to go ahead with your proposal IMO you should forgive the idea of vendor->package and use a single dimension with the package namespace `'Zend\ServiceManager' => [/* config */],`

**Comment by xtreamwayz** [comment]
> Is there a special reason why not every config key has a vendor/package name?

As Maks3w said, if I want to swap from the Aura.DI package to zend servicemanager I can right now since they all use ``$config['dependencies']``. As soon as this is prefixed you can't do this anymore.

Actually everything else besides the container (dependencies) could be prefixed since they all work differently. The dependency container doesn't matter anyway since it's used to initialize the container and after that the config is inject inside it. Or maybe you can use a ``container`` or ``container-interop`` key for it since that is what it is.

And then there is still the question, where does something like ``zend-expressive-twigrenderer`` fit in. I guess it goes into ``[zend][expressive-twigrenderer]``. Although it is twig, it uses its own factory and its own custom settings. Unless you refactor all the template renderers and routers.

As pointed out in #155 I would suggest:

```php
// container related settings
'container' => [
    'invokables' => [
    ],
    'factories' => [
        Zend\Expressive\Application::class => Zend\Expressive\Container\ApplicationFactory::class,
    ],
],

// app related settings
'app' => [
    'debug' => true,
    'config_cache_enabled' => false,
],

// vendor package related settings
'<vendor-name>' => [
    '<package-name>' => [
        'key' => 'value',
    ],
],
```

**Comment by Maks3w** [comment]
I don't see any reason for to have two levels of settings (vendor, package) learn from psr0 vs psr4. Nobody care that  vendor folder,  everyone wants the sugar inside of the component key. Use a compound key name with vendor and component together like a php namespace.

**Comment by sandrokeil** [comment]
@Maks3w 

> 1. Put limitations on config key names prevent drop in replacements by libraries which aim to fork/extend the original.

Good point, but this only works for some PSR standards. Does AURA-DI supports all the definition of the Zend Framework Service Manager like `lazy_services` or `delegators`? What's with Pimlple? I don't think there exists a real drop in replacement, but maybe I'm wrong. You need a wrapper factory or something else, but what if a config key is not supported?

> 2. If you want to go ahead with your proposal IMO you should forgive the idea of vendor->package and use a single dimension with the package namespace 'Zend\ServiceManager' => [/* config */],

PSR-4 defines *Implementors MUST use at least two namespace levels: a vendor name, and package name within that vendor.*. Maybe it's ok to put the vendor name and the package name in one key like `zend-service-manager`, but I think it's better organized in separate keys.

The Zend Expressive `container/intro.md` defines: 
*We recommend using fully-qualified class names whenever possible as service names, with one exception: in cases where a service provides an implementation of an interface used for typehints, use the interface name.*

I like this approach but what is if you need two instances of an interface/service like a database connection? Meta names should also have a clear structure. It's easier to explain naming of sevices and to find out the configuration for this service.

Any other thoughts?

**Comment by Maks3w** [comment]
The point is nobody care the organization at vendor level. Does not apport any semantic improvement. Also prevent free sort of config settings *in a single array declaration* (`[foo => [componentA], baz => [componentA], foo => [componentB]]. Last foo override previous foo declaration)

If I would like to organize settings I would do it by behavior or nature (db, cache, ... or sale, admin)

**Comment by weierophinney** [comment]
(argh! started a huge comment on this yesterday, and evidently didn't hit submit!)

From an analytical and organizational point of view, I like the *idea* of this. From the standpoint of a user and trying to understand how my configuration works together, I have some huge problems with it.

Let me tackle this with a concrete example: Apigility.

Apigility as a product uses more than a dozen modules. When configuring a REST service, you will have top-level keys for the following:

- `controllers` maps the relevant controller to the relevant factory (this will be explicit in v2 of Apigility, but implicit currently due to use of an `AbstractFactory` for loading REST controllers)
- `router` defines routes and maps them to the relevant controller
- `zf-versioning` defines the versions available for the API, which also affects the individual REST services
- `zf-content-negotiation` has 3 keys, `controllers`, `accept_whitelist`, and `content_type_whitelist`, each mapping the REST service to relevant configuration
- `zf-content-validation` maps a REST service to the relevant input filter service
- `input_filter_specs` defines the service-specific input filter(s)
- `service_manager` maps the REST resource class to its factory
- `zf-rest` maps the REST controller to configuration details, such as how to handle collections, which route maps to the service, etc.
- `zf-hal` maps the REST entity and collection classes to how they're serialized
- `zf-mvc-auth` indicates which authentication scheme is used for the API in which the REST service is defined, as well as defines authorization rules for the REST service's entities and collections

That's **10** separate keys to look under to understand **1** service. And because each key maps to a ZF module, it means that there is often configuration for *many* services, making stitching together the information tedious. (This is one reason why the UI is so useful, as it provides a visualization *per-service*!)

When we were developing the node.js version of Apigility, we took a different approach, and decided configuration should be per-service, and then provided a configuration compiler that compiled configuration for each of the various middleware that would handle the specific application aspects (authentication, authorization, negotiation, validation, etc.). This had an interesting effect: it was far easier to configure a service, because you could define all the behavior in one location. The UI was still useful, but if you couldn't use the UI, or didn't want to, it became very easy.

Also interesting is that it essentially combines both approaches: you have user-friendly configuration you can read and write, but it gets compiled down to module/middleware-specific configuration. But that becomes an *implementation detail* at best; to the user, the complexity is masked.

At a low-level, we still need some configuration organization for things like the service container and routes. But, that said, I disagree with the assertion that `vendor/package` is the correct approach. As @Maks3w notes, that approach has some disadvantages:

- It artificially pushes configuration an extra level down. You essentially cannot see any meaningful configuration values without looking at least two levels deep. This may seem trivial, but when you consider indentation, even in YAML or JSON, the further configuration is nested, the more difficult it is to read and interpret.
- It encourages package-specific configuration without regard for the impact configuration might have on other packages. As @Maks3w notes, one huge value of configuration is the possibility of merging and overrides. In other words, if configuration is general enough or could be re-used by another component, segregation by vendor/package eliminates these possibilities.

On the flip-side:

- A package could always provide both its own specific configuration, as well as configuration for overriding another package by nesting the latter under the target vendor/package.
- Grouping by behavior makes the assumption that different components can use the configuration in the same way; it often (usually?) cannot.
- Grouping by behavior often requires writing application-specific compilers and/or custom factories to ensure configuration will be useful for the application's context.

All that said: zend-expressive-skeleton is "solving" this in most cases by ensuring that the configuration generated *is specific to the components selected at installation*. While you can swap out components later, doing so *can* and *usually will* require that you make changes in your configuration. For example:

- Each of the routers with which we provide integration currently *have different route syntaxes* and *different configuration schema for providing default values and constraints*.
- While the`TemplateRendererInterface` API largely unifies things like namespace/path mappings and default variables, *any renderer-specific considerations require custom configuration*.
- The two shipped error handlers have common configuration, but the whoops error-handler *has its own specific configuration needs*.
- Service containers have highly specific configuration formats, and often quite divergent features. As such, *the way dependencies are defined and configured is dependent on the service container selected.*

My point is: I'm not sure there's any such thing as a silver bullet for configuration. I *do* support making sure that the configuration we generate and expose is *consistent*, but the real question I have is, "what does consistency of configuration mean for Expressive?" Right now, we have top-level keys for general categories that have abstractions present (e.g., dependencies, templates, routes; note that these may be general *for the selected abstraction*, as is the case for dependencies), and top-level keys for component-specific configuration that might further define behavior (whoops).

Where we're inconsistent currently is in the latter: currently, we have implementation-specific configuration for templates also mixed in with the general-level template configuration. For example, for Twig, the `templates` top-level key also contains things like the `cache_dir`, `assets_url`, `assets_version`, and `extension` — all specific to Twig — in addition to the paths and variables, which are not implementation-specific; this is true for the Plates and zend-view configuration as well. For consistency, we would want to separate those.

That said, I stand by my earlier assertion: doing so makes understanding how the configuration affects the runtime more difficult, as it splits the configuration across two separate keys, one for the abstraction and one for the implementation. It's somewhat mitigated by the fact that we keep all configuration for templates in a single file, but it still requires an understanding of how the two sets of configuration work together for the unified behavior. To me, that's the fundamental issue: how can we make the configuration *reveal intent and behavior*? Breaking it into more granular pieces split across numerous keys does not aid that goal.

**Comment by sandrokeil** [comment]
@weierophinney Thank you very much for this very detailed explanation. For me it was confusing to have one config key (e.g. `templates`) which can have different options for different factories. I understand the approach much better and this is a really good question:

> How can we make the configuration reveal intent and behavior?

For the example of templates, why not using a common `TemplateFactory` (registered in the container) and a template configuration like this:

```php
'templates' => [
    'factory' => 'FCQN of the factory which gets the options key provided',
    'options'    => [
        // e.g. twig related options or zend view ...
    ],
]
```

But it's weird, because a factory uses another factory to return the instance? And it's not working with the Apigility config.

The following config structure has the benefit to define all template related stuff under one config key. This could work work for the Apigility config, but maybe it's neccessary to register new services in the container at runtime.

```php
'templates' => [
    'FCQN of the factory which gets the options provided' => [
        // e.g. twig related options or zend view ...
    ],
]
```

These are only some ideas and maybe are useful to find a solution.

**Comment by Thinkscape** [comment]
I'd agree with @Maks3w and @weierophinney 
At scale, with big apps, large config files become a liability and one wants to manage the complexity. What I found worked best is splitting config files by aspect (group), while grouping the config keys by purpose. What I'd be looking for is **cascadability**.

I think a lot of the problems in this discussion stem from the fact, that one would want to use the "global", complete config array (tree) with a 3rd party factory. Why would you do that?

Key name clashing can only happen in case you're exchanging components that attempt to read the same key, but **it's the factory** that decides what array to use. If you're attempting to wire a 3rd party component you will write your own factory, most likely. That means that you are free to use any key name you want - be that FQDN or something else.

I can think of only a handful of examples where the clashing would actually occur and the currently proposed solutions seem like an overkill. On the other hand, the Apigility example is a great one on how apparent, component-based structure results in added complexity to seemingly simple config tasks.

**Comment by sandrokeil** [comment]
@Thinkscape I also structure my configuration according to purpose and with [interop-config v1.0.0](https://sandrokeil.github.io/interop-config/reference/examples.html#2-2-3) I added the ability to make the config structure flexible (Thanks for the suggestions here). However, my main concern was that some config keys are shared like `templates` which is used by [several factories](https://zendframework.github.io/zend-expressive/features/container/factories/) with different sub keys or some sub keys are shared like `paths`. This is a bit confusing but the factory gives an error if something goes wrong.

Think about Zend Expressive modules and each module can have different templates it's not possible to use Twig and Plates in one Zend Expressive application or you have to load config files depending on route or something else. I'm not sure if this will happen some day.

**Comment by Thinkscape** [comment]
@sandrokeil Effectively, the developer is responsible for any possible clashes when replacing components. If i.e. you switched to Aura I'd expect you to investigate what is the correct config structure and modify local files accordingly.

However, for the example you've given, the problem would be if you wanted to **use 2 templating systems at once**. If both factories consumed `templates` then stuff might break. That would be a case for grouping them by implementation.

**Comment by Thinkscape** [comment]
@weierophinney 
> It encourages package-specific configuration without regard for the impact configuration might have on other packages. As @Maks3w notes, one huge value of configuration is the possibility of merging and overrides. In other words, if configuration is general enough or could be re-used by another component, segregation by vendor/package eliminates these possibilities.

After sleeping on it, I think this might become a liability too. Consider templating:
* we assume a global `templates` key in config,
* "modules" can extend it to add-on more template paths (via config merging)
* but, there's also templating implementation (i.e. twig) which consumes not only paths but also other config
* even considering just paths, the templating implementation could be picky about the types or syntax of files in those paths

**Bottomline:** modules extending a global `templates` key **ASSUME** a particular rendering implementation and extend the config in one, particular way. 

If we had a 3 modules using `PhpRenderer` and wanted to add 1 additional module depending on `Twig`, the whole thing would collapse.

Same goes for stuff like routing, db, caching.
Special cases would include error handling (because that's handled slightly differently) and containers (as that should be interop)
 
Trying to reverse the question, I see that global, short key names are only safe assuming either:

1. the factory implementation is application-specific (domain-specific or rare),
2. or the aspect is relying on interoperability (common interface, proposal, etc.)
3. or the aspect is handled by Expressive/Stratigility internally

**Comment by Maks3w** [comment]
For to be honest. I don't think any kind of configuration normalization will success.

I found many times how the configuration its different between projects. For example you would like to normalize the payment gateway settings but many apps have more than one payment gateway with different providers or just for each currency.

Options are endless.

**Comment by xtreamwayz** [comment]
This applies to routers, containers and template engines only really. Every other package / module / dependency is out of the scope of expressive.

As far as I know expressive can't handle multiple (different) containers / template engines / routers. I think you need to change that first before even thinking about a namespace collision that might never even happen. And if the code is changed to enable multiple routers / containers / template engines it will be a breaking change.

There have been discussions about configurations keys in the past and nothing changed. Changing it now will introduce a BC anyway. So you might as well wait for it until it is really needed and the code is merged that makes it possible.
