### ISSUE TITLE
RouteResult in Router

### ISSUE THREAD

**Issue by harikt** [zendframework/zend-expressive#198]
Why is the RouteResult not saved in the Router for later usage to check the route name  used etc ?

**Comment by zf2timo** [comment]
Have a look at #187. Is this, what you are looking for?

**Comment by harikt** [comment]
@zf2timo thank you. That indeed will work.

**Comment by harikt** [comment]
oh and probably it could be saved in Router itself. So I will open this to hear from @weierophinney .

**Comment by harikt** [comment]
I can send a PR with `getRouteResult` https://github.com/zendframework/zend-expressive/blob/master/src/Router/RouterInterface.php#L43 once a route is matched. What do you think about adding this method in the interface ?

**Comment by xtreamwayz** [comment]
It's not as easy as just adding a method to the interface, you would need to implement it in all router packages as well.

``Zend\Expressive\Router\RouteResult`` is independent of the router packages. Besides that, I think it's easier to have it in the request object since that should be available in all middleware: No need to inject a router to get the route result.

**Comment by harikt** [comment]
> you would need to implement it in all router packages as well
yes.

> `Zend\Expressive\Router\RouteResult` is independent of the router packages

not sure what you were getting at. For this is independent of package.

Normally the Router is available as a view helper and the route result is getting based on the `match` method. So it seems to me,the `RouteResult` is good at Router level.

Thank you.

**Comment by harikt** [comment]
Related, I was trying to get the route result in view helper. In the `post_routing` middleware 

```php
                'post_routing' => [
			[
			    'middleware' => 'App\Middleware\RouteMatched',
			],
		],
```

I registered the middleware, but it seems not getting called. If I move the class to `pre_routing` it works. The problem is only after routing the request will contain the result. I cannot find a way to inject the request nor it have no use for it will be entirely different.

```
<?php

namespace App\Middleware;

use App\View\Helper\CurrentRoute;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Zend\View\HelperPluginManager;
use Zend\Expressive\Router\RouteResult;

class RouteMatched
{
	protected $manager;

	public function __construct(HelperPluginManager $manager)
	{
		$this->manager = $manager;
	}

	public function __invoke(ServerRequestInterface $request,
		ResponseInterface $response, callable $next = null)
	{
		$result = $request->getAttribute(RouteResult::class);
		$this->manager->setFactory('currentRoute', function () use ($result) {
			return new CurrentRoute($result);
		});
		return $next($request, $response);
	}
}
```

This is why I prefer the result in router for you can inject the router and not the request.

**Comment by danizord** [comment]
@harikt
>Why is the RouteResult not saved in the Router for later usage to check the route name used etc ?

That would make the router stateful and impossible to use `Zend\Expressive` for multiple dispatch cycles.

**Comment by simensen** [comment]
> This is why I prefer the result in router for you can inject the router and not the request.

I think this is the real problem here. I'm not sure why you think you cannot inject the request. If it is because your `post_routing` is not being run (thus, the request *you want* cannot be injected) then I think the problem you should be focusing on is why is your `post_routing` middleware not being run? If you can fix that problem it sounds like the request has what you need and your middleware will do what you want... the real problem is that your middleware doesn't seem to being run.

Am I mistaken?

**Comment by danizord** [comment]
`post_routing` won't help here because it runs after your "Action" middleware:
`pre_routing` -> `route matching` -> `"action" middleware` -> `post_routing`.

If `post_routing` is not running, thats probably because your action middleware is not calling `$next()`.

Unfortunately it is currently impossible to pipe a middleware that runs between route matching and the call of action middleware, because the routing middleware itself calls the matched action middleware. That would be possible after https://github.com/zendframework/zend-expressive/pull/192 gets merged, tough it would work only for specific routes, not globally.

**Comment by danizord** [comment]
Also, @harikt I think you can take advantage of [TemplateRendererInterface::addDefaultParam()](https://github.com/zendframework/zend-expressive/blob/996410733b629fd624e607ec52e457a95d79f189/src/Template/TemplateRendererInterface.php#L71) instead of configuring a view helper.

**Comment by harikt** [comment]
@simensen 

> I'm not sure why you think you cannot inject the request. 

What I was trying to say is `$di->set('request', $psr7request)` for the request is immutable. And it will change `with*()` method called. So you can't do the above in psr7 based frameworks.

> If it is because your post_routing is not being run (thus, the request you want cannot be injected) then I think the problem you should be focusing on is why is your post_routing middleware not being run? If you can fix that problem it sounds like the request has what you need and your middleware will do what you want... the real problem is that your middleware doesn't seem to being run.

`post_routing` is not run, and I figured it with the help of @danizord that if in your action if `$next($request, $response)` is not called the `post_routing` will never get called :-/ .

**Comment by harikt** [comment]
@danizord not sure how I can make use of `TemplateRendererInterface::addDefaultParam()` . Do you have any example for it?

**Comment by simensen** [comment]
@harikt 

>> I'm not sure why you think you cannot inject the request.
>
> What I was trying to say is $di->set('request', $psr7request) for the request is immutable. And it will change with*() method called. So you can't do the above in psr7 based frameworks.

You can totally do that in a PSR-7 framework. You just need to make sure it is injected *after* all of the other middleware have been run that might modify the request. I think the problem you are having is that you have no place to do this injection *after* the route but *before* your action is called. But it is still possible I'm not understanding the problem.

FWIW, this is similar to other problems I've been having with other systems that need to be stateless.

**Comment by harikt** [comment]
@simensen What I need is `RouteResult` from the request attribute. Two ways you can do are 

1 ) Get the `RouteResult` from the request in every action ( it is tedious ) and pass the value to `render()` .

2 ) Use a view helper, inject somehow the `RouteResult` getting from the request attribute.

In an earlier way we could have injected the `Request` as below with the help of a di container, but now your request is immutable and it changes, and you should pass it to `__invoke` and you can't do the same via injection by a di container.

```php
<?php
class ViewHelper
{
    public function __construct(Request $request)
    {
        $this->request = $request;
    }
}
```

so the above code can be changed to 

```php
<?php
class ViewHelper
{
    public function __invoke(Request $request)
    {
        return $request->getAttribute(RouteResult:class);
    }
}
```

So we need to inject the request to view data and call as `$this->currentRoute($request)` . See the hacks than the old ones :-/ .

It may be personal likes / dislikes of usage.

**Comment by danizord** [comment]
@harikt 

```php
class InjectRouteResultMiddleware
{
	private $templateRenderer;

	public function __construct(TemplateRendererInterface $templateRenderer)
	{
		$this->templateRenderer = $templateRenderer;
	}

	public function __invoke($req, $res, $next)
	{
		$routeResult = $req->getAttribute(RouteResult::class);

		$this->templateRenderer->addDefaultParam('routeResult', $routeResult);

		$next($req, $res);
	}
}
```

```php
class SomeActionMiddleware
{
	private $templateRenderer;

	public function __construct(TemplateRendererInterface $templateRenderer)
	{
		$this->templateRenderer = $templateRenderer;
	}

	public function __invoke($req, $res, $next)
	{
		return new HtmlResponse($this->templateRenderer->render('some-template'));
	}
}
```

This way you can access `routeResult` variable in all your templates.

**Comment by harikt** [comment]
@danizord Thank you.

One question : isn't I can register middleware in `pre_routing` or `post_routing` only ? I am looking at `middleware-pipe.global.php` . If it is pre, then you will not get the `route result` . I think there was something I noticed earlier. Some sort of way to call the match on router before execution. But don't remember what it was.

**Comment by danizord** [comment]
@harikt as I said in  https://github.com/zendframework/zend-expressive/issues/198#issuecomment-159313968, I'm not sure if this is possible in a clear way before #192 gets merged. But yeah you can hack this by returning a `MiddlewarePipe` with piped `InjectRouteResultMiddleware` in your action middleware factory. @michaelmoussa explains that approach in  https://github.com/zendframework/zend-expressive/issues/190

**Comment by weierophinney** [comment]
@harikt —

pre-routing middleware is middleware to execute *every* request and/or for subpaths (e.g., registering a separate middleware pipeline for URIs starting with `/api`). post-routing middleware should typically only be used for error middleware, as most routed middleware will return a response directly.

#192 is adding support for you to provide a *list*/*queue* of middleware to execute for a route match. This will allow you to do something like:

```php
'middleware' => [
    'InjectRouteResultMiddleware',
    'SomeActionMiddleware',
]
```

when defining your route, and they will be done in a chain. What I'm trying to determine is if we can also provide a way to automate this somehow, so that you don't have to do the above every time you want to do templated middleware. One idea I have is setting up a subject/observer triggered by the routing middleware with the route result, which would simplify this tremendously.

Now:

> What I was trying to say is $di->set('request', $psr7request) for the request is immutable. And it will change with*() method called. So you can't do the above in psr7 based frameworks.

The request *is not a service*. It's a *message*, representing the state when the application is executed. It *should not* be registered as a service; it *should* be passed to objects that need to know about it.

Similarly, the `RouteResult` is a *product of calculation*; it's the result of analyzing the request against a set of rules. As such, it, too, should be passed to objects interested in those results. We do that by pushing the matched parameters into a new request, as well as the RouteResult itself, so that lower layers in the system can retrieve them.

For middleware, then, getting access to this information is relatively easy. The hard part is templates, which may want access to the current matches in order to simplify URI generation. That's the part we need to solve. As noted above, #192 is one way to solve it; I'll likely also be submitting a patch with the subject/observer idea shortly, which may better answer this specific use case.
