### ISSUE TITLE
How to deal with i18n?

### ISSUE THREAD

**Issue by mtymek** [zendframework/zend-expressive#199]
Localizing application is a pretty common task. How should work in Zend Expressive app?

Usually, application will detect user's language (by reading some cookies, or by parsing user agent string), and store it inside some object ("translator"). This introduces global state, which is not desired in middleware app - it gives similar problems as passing RouteResult around. On the other hand, having single, global translator is super handy - it can be injected into view helpers, or services dealing with text output.
So, what would be the preferred way of handling this inside Expressive app? I can imagine writing middleware that detects language and passes it to inner layers, but what to do next? Where to create translator, and how to tell view helpers to use it?

**Comment by weierophinney** [comment]
@mtymek Most DI containers will return the *same instance* on subsequent calls for the same service. What this means is that middleware can manipulate such instances.

So, as an example, you could provide a pre_pipeline middleware that composes a translator instance, and manipulates it based on information it gleans from the request, returning `$next()` when complete:

```php
class I18nMiddleware
{
    private $translator;

    public function __construct(Translator $translator)
    {
        $this->translator = $translator;
    }

    public function __invoke($request, $response, $next)
    {
        $userAgent = $request->getHeaderLine('User-Agent');
        $this->translator->setLocale($this->parse($userAgent));
        return $next($request, $response);
    }

    private function parse($userAgent)
    {
        /* ... */
    }
}
```

As noted, if this is registered as pre_pipeline middleware, then it will likely get executed every request, and *always* prior to any routed middleware.

Further, since it would be manipulating a stateful object — the translator — any service (such as a view helper) in which the translator is injected is affected. This gives us the benefits of both dependency injection, as well as request-based state.

As such: in your translator instance's factory, have it return an instance with a default locale, and then register middleware such as the above to obtain and inject the request-specific locale as early as possible.

**Comment by sandrokeil** [comment]
@weierophinney These kind of thoughts would be interesting to have it in the docs or is this out of scope? I think this is useful for other people. Maybe a doc file with middleware examples or something else.

**Comment by weierophinney** [comment]
We **do** have a cookbook section already, if anyone wants to create a
recipe based on my reply...

**Comment by mtymek** [comment]
Thanks for explanation - I tried it in an app and it works well. I will draft something for the cookbook.
