### ISSUE TITLE
Cannot use multiple error middleware

### ISSUE THREAD

**Issue by nesl247** [zendframework/zend-expressive#264]
I can't seem to find how to use multiple error middleware. Once one executes, the second one never seems to.

In the first one, I do of course call `return $next($request, new JsonResponse([.., <int>]));`. I would think that I should be able to go through an infinite number of error middleware.

This brings me to the point that I don't understand why all the docs show middleware doing `return new SomeResponse(...);`. This prohibits the use of post_routing middleware. I would think almost all middleware would always return `$next($request, $response)` of some sort instead.

**Comment by weierophinney** [comment]
The rules for error middleware chaining are the same as normal middleware: calling `$next($request, $response)` will invoke the next *non-error-middleware* in the chain following the error middleware. In order to invoke the next **error** middleware, you need to pass the `$error` argument to `$next`!

So, in your example, use:

```
return $next($request, new JsonResponse(/* ... */), $error); // <-- note the last argument!
```

Regarding this:

> I don't understand why all the docs show middleware doing return new SomeResponse(...);. This prohibits the use of post_routing middleware.

Post routing middleware should really only be used for error conditions.

If you think of the pipeline as an onion, I think this becomes slightly clearer. Essentially, each time you call `$next()`, you're travelling a layer deeper towards the center of the onion. Whenever a middleware returns a response, you start the trip back *out* the onion. If you consider that error middleware happens at the inner-most layers, think of it this way: you get more tears the deeper into the onion you cut.

In most cases when I see a question such as yours, what I expect is that you are wanting to perform *post-processing* on a response. Interestingly, this is best accomplished by *pre-*routing middleware. Let me demonstrate:

```php
function ($request, $response, $next)
{
    $response = $next($request, $response);

    // inject a header into every response
    return $response->withHeader('X-Clacks-Overhead', 'GNU Terry Pratchett');
}
```

If you register the above as pre-routing middleware, then the response will be altered *for every middleware registered later in the pipeline*, including *routed* middleware.

So:

- Use pre-routing middleware for setup/bootstrapping (e.g., the `UrlHelper` and `ServerUrlHelper` middleware fall into this category).
- Use pre-routing middleware to identify error conditions early and halt execution.
- Use pre-routing middleware for caching (i.e., allow you to return early)
- Use pre-routing middleware to do response introspection or to alter responses.
- Use post-routing middleware to handle error conditions.

**Comment by nesl247** [comment]
Thanks for the correction on the error middleware there. The docs are definitely lacking on this in my opinion.

As far as the post routing middleware stuff.. While I get it, it seems counter-intuitive to the extreme.

For one, if you do as you say, and modify the response before you get to your routed middleware, when you return a new response instance, you are ignoring everything with the previous response aren't you?

Two, a pipeline is generally one direction, therefore the whole onion bit seems wrong to me. Aka, a linear path from the very beginning to the end, with forks if you encounter errors. Basically, first you have your pre-routing middleware, then you route, then you execute middleware for route matching, then you execute the middleware for the route, then you execute any post routed middleware, for things such as logging responses, adding headers, etc., and finally output the response in some manner. If an exception occurs at any point, you fork the path and handle the error. While the implementation may be done like an onion, it seems to go against all the naming that is used.

Three, if post-routing middleware is supposed to really only be used for error handling, why is error not defaulted to true to encourage the intended behavior?

**Comment by nesl247** [comment]
Just noticed I misread the little snippet of code you have, so I see how you are handling adding the header in. I also noticed there is a thread about renaming the configuration, pipeline, etc., so I'll close this out in favor of that thread.
