### ISSUE TITLE
[RC6] Adding the routing middleware in a pathed middleware fails

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-expressive#272]
Hi,

First of all congrats for the new release, definitely simplifies some of our code where we had to inject the Router.

However I've found an issue. Not sure if this is the wanted behaviour. Given this config:

```php
return [
    'middleware_pipeline' => [
        [
            'path'       => '/apps',
            'middleware' => [
                ApplicationFactory::ROUTING_MIDDLEWARE,
                AppInitializerMiddleware::class,
                VerifyRequestMiddleware::class,
                AuthenticationMiddleware::class,
                ApplicationFactory::DISPATCH_MIDDLEWARE
            ],
        ]
    ],
];
```

I'd expect the routing to work on any `/apps` path. However, adding a simple var_dump($request->getAttribute(RouteResult::class)) on the `AppInitializerMiddleware` returns null (it sounds expected on a path like "/foo/bar", but on a path "/apps/bar" I would expect a result.

Adding the routing middleware globally works though:

```php
return [
    'middleware_pipeline' => [
        [
            'middleware' => [
                ApplicationFactory::ROUTING_MIDDLEWARE
            ]
        ],

        [
            'path'       => '/apps',
            'middleware' => [
                AppInitializerMiddleware::class,
                VerifyRequestMiddleware::class,
                AuthenticationMiddleware::class,
                ApplicationFactory::DISPATCH_MIDDLEWARE
            ],
        ]
    ],
];
```

**Comment by weierophinney** [comment]
What routes are defined, exactly? Is it defining a `/bar` route?

Expected behavior when you push the routing middleware under a path-based middleware specification is that it will match *relative* to that path. In the case you note above, if you have a route that matches `/bar[/:id]`, it would match on the URI `/apps/bar/f00`, as the request path it would receive would have stripped out the `/apps` segment. (It would also match on `/bar/foo`!)

So, essentially: I need to know what routes you're defining before I can understand if it's expected behavior, or a bug.

**Comment by bakura10** [comment]
Sure. Here are the routes:

```php
'routes' => [
        [
            'name'            => 'internal.ping',
            'path'            => '/internal/ping',
            'middleware'      => App\Action\PingAction::class,
            'allowed_methods' => ['GET']
        ],

        [
            'name'            => 'shopify.entry-point',
            'path'            => '/apps/{app_id}',
            'middleware'      => App\Action\EntryPointAction::class,
            'allowed_methods' => ['GET']
        ],

        [
            'name'            => 'shopify.oauth.callback',
            'path'            => '/apps/{app_id}/oauth/redirect',
            'middleware'      => App\Action\CallbackAction::class,
            'allowed_methods' => ['GET']
        ]
    ],
```

**Comment by weierophinney** [comment]
@bakura10 and what path is failing routing?

**Comment by bakura10** [comment]
Actually any path starting by apps ("/apps/gtgrtgtg"). Retrieving the RouteResult in a middleware registered in the same sub-path list of middlewares return null.

**Comment by weierophinney** [comment]
@bakura10 The behavior makes sense, then.

The confusion is that both *routed* middleware and *pipeline* middleware can define *paths* in their specifications. For *routed* middleware, this is a *routing* specification — which *can* be a literal, but which often typically some sort of matching rules. For *pipeline* middleware, this is a *literal* path prefix *only*, and that prefix is *stripped* when the request is passed to the middleware it matches.

In your examples above, if you push the routing middleware under the `/apps` path, when it receives a request, it will receive it *without the `/apps` prefix in the path*. As such, it's getting `/gtgrtgtg` as the path (per your sample URI), not `/apps/gtgrtgtg`. That's why it worked in your second example (routing was happening against the full request path), but not the first.

The `path` key in the middleware specification is for path-based segregation. If that initial path is matched, the middleware is dispatched *without the matched path segment*. This is to allow you to compose middleware that does its own routing; it then does not care what the base path is, only that it can route the paths provided to it.

As an example, let's say I create an API middleware that can handle the path segments `/ping` and `resource[/{id}]`:

```php
$api->get('/ping', $pingMiddleware);
$api->any('/resource[/{id}]', $resourceMiddleware);
```

Further, let's say I have a factory that will return the `$api` instance.

Now let's say I want my API to be under the top-level path `/api`. I can compose it in an Expressive application as follows:

```php
return [ 'middleware_pipeline' => [
    [
        'path' => '/api',
        'middleware' => ApiMiddleware::class,
        'priority' => 1000,
    ],
]];
```

(Note: I use priority 1000 so it intercepts before my normal application routing middleware!)

When a request for a URI starting with `/api` comes in, it will execute this middleware. As examples:

- `/api/ping`
- `/api/resource`
- `/api/resource/foobar`

Internally, a new request is passed to the `ApiMiddleware` that strips out the `/api` segment, which means that the `ApiMiddleware` is handling the following paths instead:

- `/ping`
- `/resource`
- `/resource/foobar`

This means that we can use our `ApiMiddleware` under a new top-level path *with zero changes*.

What this means for you right now is that you need to make one of two changes:

- Strip the `/apps` segment out of your routes. If you're going to have the middleware executing under a subpath, that subpath gets stripped out, so make the routes relative to the root.
- Alternately, don't specify the subpath when defining the middleware specification.

**Comment by bakura10** [comment]
This is crystal clear. Thanks a lot for the clarification :).

Envoyé de mon iPhone

**Comment by bakura10** [comment]
Hi again,

I have a similar question (somewhat related), I suppose, but still, I'm not sure if this is the expected result or not.

I have the following route:

```php
        [
            'name'            => 'api.subscriptions.get',
            'path'            => '/apps/{app_id}/subscription',
            'middleware'      => App\Action\GetSubscriptionAction::class,
            'allowed_methods' => ['GET']
        ],
```

And the following pipeline:

```php
'middleware_pipeline' => [
        [
            'middleware' => [
                BodyParamsMiddleware::class,
                ApplicationFactory::ROUTING_MIDDLEWARE,
            ]
        ],

        [
            'path'       => '/apps',
            'middleware' => [
                AppInitializerMiddleware::class,
                AuthenticationMiddleware::class,
            ]
        ],

        [
            'middleware' => [
                ApplicationFactory::DISPATCH_MIDDLEWARE
            ]
        ]
    ],
```

If I go to URL "/bar", I have a 404. Expected.

However, if I go to the URL "/apps", I don't have a 404. Instead, it entered into the AppInitializerMiddleware. The funny thing is that retrieving RouteResult from the request return null, hence confirming the router has been unable to match anything.

However considering that the router has failed to match something, I'd expect it to return a response directly no? Or did I misunderstood and the Routing just does not return the response?

**Comment by weierophinney** [comment]
@bakura10 — The problem is that you're mixing routed and path-based middleware.

Path-based middleware uses Stratigility's static, literal path-matching. When it does so, it strips the matched path and executes the next deeper layer of middleware with a request that omits it.

Route-based middleware does not. In Expressive, routing does the following:

- Passes the request to the router to match.
- If the result is a failure, it does one of two things:
  - For failures due to method, it sets a 405 response status, an Allow header with allowed methods, and then calls `$next()` with the error parameter set to 405.
  - Otherwise, it just calls on `$next()`
- If the result is a success, it creates an updated request that includes all route match parameters as request attributes, as well as an route result attribute with the route result.

The thing to note is that for failed routing, no route result is injected, and it calls on the next middleware. This allows you to have later middleware to try and handle the request. In fact, it's [one of the documented ways of creating 404 handlers](http://zendframework.github.io/zend-expressive/cookbook/custom-404-page-handling/)!

What you have above are two separate things:

- Route-based middleware matching on `/apps/{app_id}/subscription`
- Path-based middleware matching on the path `/apps`

When you go to the URL `/apps`, you'll hit that path-based middleware, despite the fact that no route was matched; this is because it's the next middleware in the stack! And it correctly has a null route result, because the results of routing were that it failed to route. As noted above, this is to allow a lower layer to try and handle the request; if none can, then eventually it gets to the final handler, which will create and return a 404.

**Comment by danizord** [comment]
@weierophinney 

>The thing to note is that for failed routing, no route result is injected, and it calls on the next middleware. 

Why it does not call next error middleware by passing 404 as third argument?

**Comment by weierophinney** [comment]
> Why it does not call next error middleware by passing 404 as third argument?

Because it's not an error condition; failure to route means we should move on to the next middleware in the stack.

Passing the error argument won't move to the next middleware in the stack, it moves to the next *error* middleware in the stack, which you may not want, particularly as error middleware are typically pushed at the end of the pipeline. Having the routing middleware call `$next()` without the error argument allows us to recover; for instance, you could have middleware in between the routing and dispatch middleware that, on route failure, injects a route result representing an application-specific page (such as search) that the dispatch middleware can then handle.

**Comment by danizord** [comment]
>Because it's not an error condition; failure to route means we should move on to the next middleware in the stack.

In my point of view, failure to route means no resource was matched for given URI, so 404.

>Passing the error argument won't move to the next middleware in the stack, it moves to the next error middleware in the stack

That's actually what I expected. After routing I have authentication, authorization and body parsing middlewares and I don't want to authenticate/authorize/decode a request for a resource that was not found.

>Having the routing middleware call $next() without the error argument allows us to recover; for instance, you could have middleware in between the routing and dispatch middleware that, on route failure, injects a route result representing an application-specific page (such as search)

Yeah, I think this is error handling, so that it fits well a error handler middleware.

Anyway, I think there's no chance to change this behavior since we released stable, but this behavior is a bit counter-intuitive IMHO and therefore should be documented somewhere to advertise people that failed route match is not handled as error in Expressive.

**Comment by weierophinney** [comment]
> In my point of view, failure to route means no resource was matched for given URI, so 404.

With a middleware stack, failure to route simply means that the next middleware should attempt to handle the request.

> I don't want to authenticate/authorize/decode a request for a resource that was not found.

If you are doing your authentication/authorization/decoding/whatever between routing and dispatch, you should be checking first if you have a route result and/or what route was matched *anyways*.

> I think this is error handling, so that it fits well a error handler middleware.

As noted above, *failure to route simply means that the next middleware should attempt to handle the request*. It's not an error condition; it's one expected outcome.

I personally think we've messaged this within the documentation, particularly by having [recipes for doing custom 404s](http://zendframework.github.io/zend-expressive/cookbook/custom-404-page-handling/), and detailing that middleware between routing and dispatch can introspect the route result (or lack thereof). If you feel more docs are required, do, please, create a pull request.
