### ISSUE TITLE
Add error middleware, whoops not shown, but instead 404 page shown

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-expressive#281]
steps to reproduce:

- use zend-expressive-skeleton with whoops
- call `throw new \Exception('foo')` in `HomeAction::__invoke()` 
- set error middleware
```php
        'error' => [
            'middleware' => [
                // Add error middleware here.
                function ($error, $req, $resp, $next) {
                    // do log error here...
                    // do other here ...

                    return $next($req, $resp);
                },
            ],
            'error'    => true,
            'priority' => -1000,
        ],
```
- got 404 page instead of normal whoops
![error-middleware](https://cloud.githubusercontent.com/assets/459648/12539610/abd49e6c-c329-11e5-9f78-52fe174597e1.png)

**Comment by weierophinney** [comment]
You should pass the error argument when calling `$next` once you hit any error middleware: `return $next($request, $response, $error)`. Otherwise it tries to find the next normal middleware in the stack, *and your error is then lost.* In this case, it means that you also have an unmodified response, which leads to the 404. Pass the error when calling `$next ` from your error middleware, and you'll get a proper error response.

**Comment by samsonasik** [comment]
oh yeah, problem solved. Thanks ;)

**Comment by Ocramius** [comment]
@samsonasik consider checking if the docs aren't clear enough on this

**Comment by samsonasik** [comment]
@Ocramius yes, it seems we need add documentation for it
