### ISSUE TITLE
Docs: JSON examples are missing language-json html class

### ISSUE THREAD

**Issue by juokaz** [zendframework/zend-expressive#302]
See here:
<img width="558" alt="screen shot 2016-01-28 at 1 43 10 pm" src="https://cloud.githubusercontent.com/assets/157597/12655059/197421f2-c5c5-11e5-8dbe-09bd6e582990.png">

This is because the `<pre>` block does not have a class `language-json`. This might be a bug in https://github.com/zendframework/zf-mkdoc-theme instead of this (because the docs do specify json as a codesample type), but I was not able to figure out why pygments/codehilite are not outputting it. 

P.S.
Congrats on 1.0.0!! :fireworks:

**Comment by weierophinney** [comment]
@juokaz We're not using pygments or codehilite; we're using prismjs, and that leads to the root cause: when I created our prism CSS and JS builds, I evidently missed a couple languages, including JSON and Twig. Updated now with the zf-mkdoc-theme 0.2.7, and re-running the latest build appears to fix the issue.
