### ISSUE TITLE
Zend router - child routes

### ISSUE THREAD

**Issue by vaclavvanik** [zendframework/zend-expressive#336]
Hi, is there any way how to configure expressive router to use zf2 router's child routes?

**Comment by weierophinney** [comment]
Currently, no, though I think @DASPRiD was working on a solution.

The reason is this: zend-router is the only router we've run across that supports such a feature, and adapting other routers to support it was going to be hugely difficult, and complicate adding middleware to a large degree. As such, the `RouterInterface` targets the most common featureset common across routing implementations.

You can, of course, slipstream in your own routing middleware to allow it, however.

**Comment by vbogoev** [comment]
Any progress? I'll use zend-expressive for big project and I'll need child routes for sure...

**Comment by harikt** [comment]
Hi @vbogoev ,

I have not integrated zend-router, but as zend-router is integrated to expressive, in that case you can first instantiate the router and make / load the necessary changes to make that happen.

But if you are looking at the `config/autoload/routes.global.php` then probably there is no way I guess.

The same concept can be applied to Aura.Route attaching groups. But it is not the way zend-mvc-router did. Keeping the link in case you want to look into it https://github.com/auraphp/Aura.Router/tree/2.x#attaching-route-groups .

**Comment by tasmaniski** [comment]
I guess there will be no support for this feature?

**Comment by michaelmoussa** [comment]
There are no plans to implement this officially right now, but we could
look at contributions for it.

On Tue, Oct 25, 2016 at 9:40 AM Alex <notifications@github.com> wrote:

I guess there will be no support for this feature?

—
You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub
<https://github.com/zendframework/zend-expressive/issues/336#issuecomment-256037368>,
or mute the thread

**Comment by xtreamwayz** [comment]
I knew zend-router supports it but I didn't know [FastRoute](https://github.com/nikic/FastRoute#route-groups) and [Aura.Router](https://github.com/auraphp/Aura.Router/blob/3.x/docs/attaching-route-groups.md) supported it in some way as well.

How hard would it be to implement this? I'm not thinking about actual using the child routes and groups of the specific routers since they seem to differ too much. I was thinking about doing it the FastRoute way and transform the child routes to normal single routes while they are being added. So just prefix a child route with its parents path. Could it be really that simple or am I missing something?

```php
$app->addGroup('/blog', function (Application $app) {
    $app->route('/', Action\BlogIndexAction::class, ['GET'], 'blog');
    $app->route('/feed.xml', Action\BlogXmlFeedAction::class, ['GET'], 'feed');
    $app->route('/{id:[0-9a-zA-Z\-]+}', Action\BlogPostAction::class, ['GET'], 'blog.post');
});
```

Would translate to:

```php
$app->route('/blog', Action\BlogIndexAction::class, ['GET'], 'blog');
$app->route('/blog/feed.xml', Action\BlogXmlFeedAction::class, ['GET'], 'feed');
$app->route('/blog/{id:[0-9a-zA-Z\-]+}', Action\BlogPostAction::class, ['GET'], 'blog.post');
```

**Comment by tasmaniski** [comment]
In my case it's not only in naming URLs.

For eg. at Admin panel I want to check the whole group instead of single route. 
Of course I can extract route name. In my case would be **admin.post**, **admin.category**, **admin.comments** ... And than to _**have my custom convention**_ to explode route name by dot and than to check if user have permission for "**admin**" group.

so, it would be much clearer if there is a grouping routes.

**Comment by xtreamwayz** [comment]
@tasmaniski Checking the group is not possible. At least not with FastRoute. If you add a group, FastRoute internally translates all child routes into single routes. So internally the complete grouping does not do what you want it to do.

Checking the route name or add route options (`'_security' => 'admin'`) might work for you.

**Comment by MatthiasKuehneEllerhold** [comment]
@xtreamwayz How can I use route groups myself? I'd have to add them to the router myself. Completly ignore the application and route collector. 
This way I cant change my router (e. g. from FastRoute to ZendRouter) any more.
Are there any more drawbacks to this?
