### ISSUE TITLE
Components navigation broken

### ISSUE THREAD

**Issue by atlantic8-web** [zendframework/zend-expressive#367]
Impossible to click on the components list dropdown menu in Chrome http://zendframework.github.io/zend-expressive/

**Comment by froschdesign** [comment]
Error:

> XMLHttpRequest cannot load http://docs.zendframework.com/zf-mkdoc-theme/scripts/zf-component-list.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://zendframework.github.io' is therefore not allowed access.

**Comment by harikt** [comment]
or probably the links should be changed to make use of https://docs.zendframework.com/zend-expressive/ .

**Comment by weierophinney** [comment]
The issues are multiple:

- The zf-mkdoc-theme is using `//` notation for the `zf-component-list.json`, which means that it will request it using SSL if SSL is enabled, but over vanilla HTTP otherwise. The problem, however, is that our web server was configured to redirect any non-SSL requests to the SSL variant, which is why the CORS header was not present. (XHR does not follow redirects by default!)
- The second issue is that we still have a lot of links pointing to zendframework.github.io, vs docs.zendframework.com; it will take some time to find and update all of those.

In the short-term, we've added a rule to our proxy setup to no longer force SSL for the zf-component-list.json asset, ensuring that an XHR to that asset will work correctly regardless. I've verified that it works correctly at this time.
