### ISSUE TITLE
Routing: Middleware is required but optional on Route

### ISSUE THREAD

**Issue by mwillbanks** [zendframework/zend-expressive#38]
The middleware is required but optional on route.  In addition, by making middleware required when using the router will defeat default routes / segment routing which IMO should be allowed.

**Comment by mwillbanks** [comment]
Basically this is how i think it should work:

```
$route = new Route('/path/to/something');
$route->setOptions([ .... ]); // say options contains something that I can determine how to marshal a route from
$app->addRoute($route);
$app->run(); 
```

I would expect that I can determine how to marshal my own route (which would be nice if that method was not private fyi).  This way, a middleware is not required but it is expected to be returned at some point (right now it cannot be due to the definition of the routers).

**Comment by weierophinney** [comment]
> I would expect that I can determine how to marshal my own route

I'm assuming you mean "middleware" and not "route" in the above.

So, here's an idea: have the middleware registered with the route contain the logic it needs to marshal _additional_ middleware:

```php
$route->setMiddleware(function ($request, $response, $next = null) use ($route) {
    // Pull from the route options if necessary, or the request, etc. to do more calculations...
    // and then:
    return $discoveredMiddleware($request, $response, $next);
});
```

Would this solve your problem?

---

Regarding this:

> The middleware is required but optional on route.

No, it's required:

- https://github.com/zendframework/zend-expressive/blob/master/src/Router/Route.php#L61-L69

The reason `Application::route()` has `$middleware` as optional is to allow passing a `Route` instance to the method, vs data to use for *creating* a `Route` instance. If you look in the logic, we raise an `InvalidArgumentException` if the first argument is not a `Route` instance, and `$middleware` is missing.

---

Regarding:

> by making middleware required when using the router will defeat default routes / segment routing which IMO should be allowed.

I think I'm either not understanding the problem, or I need to write documentation. :)

If by a "default" route, you mean a "catchall" to execute when no other route matches, we already have that facility; it can be accomplished in two separate ways:

- After any call to `route()`, or after piping `Application::routeMiddleware` manually, you can `pipe()` your "fallback" middleware:

  ```php
  $app->route(/* ... */); // repeat as needed

  $app->pipe($fallbackMiddleware);
  ```

  This will execute if no routes match.

- Alternately, build a custom "final handler" implementation, and inject it when you create your `Application` instance. The final handler is called when the middleware stack is exhausted, but no middleware has returned a response. `Zend\Stratigility\FinalHandler` currently:

  - checks to see if the received response is different than the one it was seeded with, and, if so, returns it.
  - Next, it checks to see if the response body size has changed, and, if so, returns the response.
  - Finally, it returns a 404.

  (If an error was passed to it, it returns an error response, building it if necessary.)

  What this means is that you could create a custom one to execute in the event no middleware executes and/or no middleware returns a response, and have it be your "default" handler.

Would any of these solutions work for you?

--- 

Regarding segment routes, I'm not sure what you're getting at; can you define what you mean by "segment route" in this context?

I ask, because I can think of two contexts.

First, defining routes that require placeholder values, such as `/resource/{id}`, or `/resource/:id`. These are already supported by the various routing backends we support.

The second is the idea of having routes match based relative to the path on which the middleware was registered. As an example of that, consider an API; you might create your middleware with routes like:

- `/user{/:id}`
- `/media/:type{/:id.:format}`
- etc.

However, you want to compose the API into an application, and have the URIs start with `/api`. This, too, is already supported:

```php
$api = createApiApplication();
$app = AppFactory::create();
$app->pipe('/api', $api);
$app->route(/*...*/);
```

Are either of these what you're getting at?

**Comment by mwillbanks** [comment]
Alright, here is the take on segment routing as I have a few minutes of time now...

One of the nice things for "segment" routing is such that I could do the following:

```
/user/{action}
```

Or something to that degree but then resolve that to something of the likes of:

```
UserController::{action}Action
```

I did get around this but it's slightly ugly but utilizes the ```$next``` parameter to be able to continue on.  The case is really handled that the middleware action is an invokable controller that then takes the parameter and checks to see if it has an action for it, if it does not it returns ```$next();```

The next issue that is commonly run into is children routing which is presently difficult to do but can be achieved through the use of multiple pipes as you brought forward.  Although, what does solve this issue is the first aspect of the middleware that you brought up and would likely actually handle it quite well.
