### ISSUE TITLE
Incompatible EmitterInterface implementation

### ISSUE THREAD

**Issue by snapshotpl** [zendframework/zend-expressive#417]
`EmitterInterface` not define any returned value of `emit` method. However `EmitterStack`:
1. Make a comparsion `if (false !== $emitter->emit($response)) {`
2. Return by self `null` or `false`.

I don't see any practical usage of `EmitterStack`. Are we need it? If yes - is it good project to keep it? Maybe should we move it into `zend-diactoros`?

**Comment by weierophinney** [comment]
Please see the [pull request where EmitterStack was introduced](https://github.com/zendframework/zend-expressive/pull/7#application) for details on why it exists. The short version is: to allow having multiple strategies for emitting a response based on the response type. Yes, PSR-7 defines the standard response interface, but in some cases, there may be optimizations to make when emitting a response based on its type: streams can be emitted iteratively if you have potentially large content (see the `SapiStreamEmitter`) or all at once if that content is small (see the `SapiEmitter`); iterators can likely be emitted via the `SapiEmitter` safely, as all data is in memory already anyways, but a generator-backed emitter might be better emitted iteratively (where `read()` might return the result of a single `yield` at a time); an emitter might look differently in an async project than a standard SAPI-targetted project.

The `EmitterInterface` _deliberately_ does not define a return type. This is because _most_ emitters will likely do something with the output buffer, and thus a return value will not be important. However, the `EmitterStack` allows an emitter to return a value, which allows the stack to determine if an emitter has done its work or not, and it does so by returning a boolean `false`; when that happens, the `EmitterStack` knows that the emitter was unable to do its job, and moves on to the next.

Within Expressive, we compose an `EmitterStack` by default, composing an `SapiEmitter`; since the stack is a stack, and thus LIFO, this emitter will be executed *last*, which is good as it can *always* handle any given PSR-7 response type. This allows users to immediately push other more specific emitters onto the stack if they want to, and they will have priority.

So, all of this is my verbose way of saying, yes, it serves a purpose.

Should it move into Diactoros? Maybe. We pushed it into Expressive because we saw a need, and, at the time, we weren't sure if there was a more general rationale for putting it in Diactoros. Moving it there, however, has BC implications; we cannot simply remove it from Expressive, as folks may be using it. We'd have to do it in a tiered fashion, having a new minor release of Expressive modify the class to extend the one from Diactoros, and then in the next major release removing it from Expressive.

If you're interested in doing so, feel free to open a PR against the Diactoros library to get things started.

**Comment by snapshotpl** [comment]
I don't see any existing implemenentation which return boolean `false`. How we can optimize it using EmitterStack? If we want to emit response in other way we can do it by inject different implementation of `EmitterInterface`

**Comment by weierophinney** [comment]
> I don't see any existing implemenentation which return boolean false.

**YET**. I have some ideas around this, but haven't had a chance to implement them.

The reason for a stack is because the application can have *one* emitter, but you may need *multiple* emitter strategies to handle different types of responses that may occur in your application. Injecting a single different implementation *may not work* in that situation.
