### ISSUE TITLE
Empty response body

### ISSUE THREAD

**Issue by Sufir** [zendframework/zend-expressive#459]
I need logging response. I add middleware with lowest priority:
```
        'latest' => [
            'middleware' => [
                \App\Middleware\LogResponseMiddleware::class,
            ],
            'priority' => -50000,
        ],
```
```
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next)
    {
        $this->logger->debug('Response', [
            $request->getMethod() => (string) $request->getUri(),
            'response' => $response->getBody()->getContents(),
            'headers' => $response->getHeaders(),
        ]);

        return $next($request, $response);
    }
```

On output I see correct response, but in middleware body and headers empty.

`[2017-03-03 11:32:26] main.DEBUG: Response {"POST":"http://ze.local/gui/","response":"","headers":[]} []`

My [middleware-pipeline.global.php](https://gist.github.com/Sufir/1d710166a38cb9ce4db48aa20f101489)

**Comment by Xerkus** [comment]
`$next()` is returning response, it is the one you need.

**Comment by Sufir** [comment]
```
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next)
    {
        $response = $next($request, $response);
        //var_export($response->getBody()->getContents()); die;

        $this->logger->info('Response', [
            $request->getMethod() => (string) $request->getUri(),
            'response' => $response->getBody()->getContents(),
            'headers' => $response->getHeaders(),
        ]);

        return $response;
    }
```
```[2017-03-03 12:16:03] main.INFO: Response {"POST":"http://ze.local/gui/","response":"","headers":[]} []```

It still empty

**Comment by weierophinney** [comment]
First, @Xerkus is correct, and your updated middleware is better. However, one thing to note is that `getContents()` on any message returns the contents _from the current pointer position_. Since write persons leave the pointer at the end of the stream, that will result in an empty string. As such, you need to do one of two things:

- Call `rewind()` on the response body before retrieving its contents
- cast the response body to a string (which performs an implicit rewind)

**Comment by Sufir** [comment]
@weierophinney it worked, thanks!
