### ISSUE TITLE
Optional route params not work

### ISSUE THREAD

**Issue by mano87** [zendframework/zend-expressive#477]
Hello,
unfortunately my optional parameter [:id] does not work. Also with all other modules we get the error "Missing parameter id". Why? What ist wrong?

**module/User/src/ConfigProvider.php:**
```
public function getDependencies(): array
{
    return [
        'delegators' => [
            Application::class => [
                RouterDelegatorFactory::class,
            ],
        ],
        'factories' => [
              // many other things
        ],
    ];
}
```

**module/User/src/config/RouterDelegatorFactory.php:**
```
class RouterDelegatorFactory implements DelegatorFactoryInterface
{
    public function __invoke(ContainerInterface $container, $name, callable $callback, array $options = null)
    {
        $application = $callback();
        $application->route('/user/profile[/:id]', UserProfileAction::class, ['get', 'post'], 'user.profile');

        return $application;
    }
}
```

**Comment by xtreamwayz** [comment]
I might be wrong here but after some research I found out that optional parameters with zend-expressive-zendrouter are not what you think they are.

They seem to be optional as in http://example.com/user/profile will be matched to that route. But when generating the route it expects a value for the `id`. You can set it like this:

```php
$application->route('/user/profile[/:id]', UserProfileAction::class, ['get', 'post'], 'user.profile')->setOptions([
    'defaults' => [
        'id' => ''
    ]
]);
```

When it has a default it will work, but not as you intended. What you can do is 
- create 2 routes; 1 for `user.profile` without the id and another one for `user.profile.id` with the id.
- or use zend-expressive-fastroute which supports optional parameters.

**Comment by mano87** [comment]
@xtreamwayz 

Basically this works. However, a final "/" is always added when the route is called. This slash should also be optional, right? What is wrong

**Comment by xtreamwayz** [comment]
That's what I'm trying to explain. It seems to be optional when trying to match a request to that route. But it's not optional when generating a route. See my explanation above.

Since you use an empty string as the `id`, it will render that `/` at the end and an empty string for the `id`.

So I suggest to use FastRoute which does exactly what you want or create a second route:

```php
$application->route('/user/profile', UserProfileAction::class, ['get', 'post'], 'user.profile')
$application->route('/user/profile/:id', UserProfileAction::class, ['get', 'post'], 'user.profile.id')
```

**Comment by weierophinney** [comment]
BTW, the way this is "solved" in ZF2 is either as @xtreamwayz details (multiple routes), or using _child routes_ (where `/user/profile` would be the parent, and `/:id` would be the child). The result is the same, though: when generating the URI, you would need to pick either the parent _or_ the child to generate, and, if using the child route, provide a non-empty `id` parameter.

To be honest, I would use FastRoute when using Expressive, as:

- it handles optional parameters in a more predictable fashion
- it's faster
- you can include your constraints directly in the route definition, reducing verbosity

**Comment by mano87** [comment]
Now we will use fastroute. However it is very stupid that the zend-router does not support these default requirements in Expressive :-/

**Comment by weierophinney** [comment]
> However it is very stupid that the zend-router does not support these default requirements in Expressive

Please be more thoughtful in your replies; calling a decision "stupid" is disrespectful to those who have put time and effort into the code that _you_ get to use _for free_.

Different routing implementations will have different features. The routing abstraction in Expressive is for the basic functionality we want to ensure works across all implementations, and is restricted to how routes are registered with the application, and how URIs based on named routes are generated. How each handles things like parameter matching and substitution is completely up to the given router; these differences in router implementations also provide you, the user, with information on which router might be a better fit for your application. If a given router does not provide the features you need, check to see if another does. That's the whole reason we allow you to choose a router, instead of dictating a single router.

Alternately, open an issue against a given router implementation to request the feature or a bugfix; better yet, provide a pull request with the change!
