### ISSUE TITLE
Missing Zend Expressive 3 dependencies config format

### ISSUE THREAD

**Issue by oshdev** [zendframework/zend-expressive#588]
As per suggestion #372 it seems that Zend Expressive uses the following format: https://github.com/gabbydgab/zend-expressive-config-provider/blob/develop/src/ConfigProvider.php#L29
Can we please have those documented or even better - if possible - create an interface(s) so we could create adapters for various container implementations with ease and perhaps include more of the popular ones to the https://github.com/zendframework/zend-expressive-skeleton installer.
For more information see https://discourse.zendframework.com/t/zend-expressive-3-dependencies-config-format/531

**Comment by weierophinney** [comment]
@oshdev I can certainly document what configuration we expect to work across all implementations. However, _how the implementations consume that configuration_ is really up to each.

We've started splitting that task into separate packages; you can see those here:

- https://github.com/zendframework/zend-auradi-config
- https://github.com/zendframework/zend-pimple-config

Ideally, we should expose these as composer plugins or to a composer plugin in order to copy artifacts into the project (e.g., to copy in the `config/container.php` file); we'll likely do that in the future.

In the meantime, I'll add a document detailing what config features implementors need to be compatible with.
