### ISSUE TITLE
Factory backed pipelines cannot be composed/nested in other pipelines

### ISSUE THREAD

**Issue by gsteel** [zendframework/zend-expressive#645]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I'm trying to compose pipelines with MiddlewareFactory and MiddlewareContainer where pipelines are retrieved from the container and composed into another pipeline for routing or whatever. For example, the pipe to process might look something like this:

- Pipe 1
   - (string) Pipe 2 Alias Name From Container. Does not return a response
   - (MiddlewarePipe) Pipe 3. Does not return a response
   - (RequestHandler) Maybe a template renderer or something

### Code to reproduce the issue

I created a failing test case illustrating what I'm trying to achieve: https://gist.github.com/gsteel/f6a5b2a45fd1630139e907e75fc94299

### Expected results

I'd expect the nested Pipe _(Pipe 2)_ to execute, followed by Pipe 3 then the final handler.

### Actual results

A Zend\Stratigility\EmptyPipelineException is thrown once Pipe 2 has been exhausted.

### Workaround

If Pipe 2 is retrieved from the container and the instance is composed into pipe 1 instead of it's identifier in the container then processing continues as expected, but this means that pipe cannot be lazy loaded

**Comment by weierophinney** [comment]
Okay, I've been able to create a small project that has the dependencies necessary to run the test, and verified the behavior.

For those who have clicked through to the gist, it's the second test that fails. Essentially, the first middleware executes, and then it descends into the nested pipeline, which executes correctly - but once complete, it does not return to the parent middleware.

This is quite odd, as this is almost exactly the sort of behavior that occurs when you run routed pipelines, which definitely work!

I need to investigate more here to determine if the issue is with how the `MiddlewareFactory` is creating the nested pipeline, or if there's an issue within `MiddlewarePipe` that needs to be resolved. I'll post more when I've had more time to investigate.

**Comment by gsteel** [comment]
That's great! Thanks ever so much - That test I wrote is a country mile from succinct I'll agree 😂
