### ISSUE TITLE
Integration with Aura.View

### ISSUE THREAD

**Issue by harikt** [zendframework/zend-expressive#94]
Hi, 

Was trying to integrate Aura.View. A few things I noticed are aura uses 2 step view and expects layout and view to be passed. And the current `render` only accepts view name and params.

https://github.com/zendframework/zend-expressive/blob/53e54efbee22cb36e2910d003ad2738cf9ca7f9b/src/Template/TemplateInterface.php#L22

I am having an idea of pushing something like `render('view::layout', $params)` same for many of the functionalities. Do you have any thoughts on this ? Or do you think you guys can keep an optional $layout = null in the render ?

**Comment by harikt** [comment]
Actually many months back I implemented something https://github.com/cocoframework/Cocoframework.Renderer/blob/master/src/RendererInterface.php#L9 . This was the signature .

```php
render($data, $view, $layout = null);
```

Not sure if the interface can be changed to something similar.

**Comment by weierophinney** [comment]
Take a look at the zend-view documentation. I'd argue that layout functionality is something that the individual adapters should address, either by abstracting it, or providing documentation on how to achieve it (which is what I did with the zend-view documentation).

In this case, I'd see the possible approaches:

- Inject the layout to use during instantiation. This approach means that middleware can safely ignore the concept within middleware.
- Allow passing the layout as a variable during rendering:
  ```php
  $html = $templates->render('blog::entry', [ 'entry' => $entry, 'layout' => 'app::layout']);
  ```
- Combine the above; if no layout is provided when rendering, use the default, if present. (A special value, such as `false`, `null`, or a constant value could be used to disable rendering the layout.)

For what it's worth, I'm considering adopting this approach for zend-view as well,as it would abstract the concept of doing a full layout. I'm also definitely considering abstracting the namespace functionality, so that the same namespace notation can be used across any adapter.

**Comment by weierophinney** [comment]
@harikt Please see #96 for the zend-view rewrite.
